import type { Metadata } from "next";
import { cn } from "@/lib/utils";
import "../styles/globals.css";
import { anton, inter, sourceSans3, tajawal } from "@/lib/fonts";
import ClientContext from "@/app/clientContext";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Props = Readonly<{
  children: React.ReactNode;
}>;
export default function RootLayout({ children }: Props) {
  return (
    <html lang="en">
      <body
        className={cn(
          inter.className,
          anton.variable,
          tajawal.variable,
          sourceSans3.variable,
          "min-h-screen",
          "flex",
          "bg-zinc-950",
          "overflow-x-hidden",
        )}
      >
        <ClientContext>{children}</ClientContext>
      </body>
    </html>
  );
}
